### ISSUE TITLE
Error in post-command-hook: (wrong-type-argument characterp nil)

### ISSUE THREAD

**Issue by dmwelch** [ppareit/graphviz-dot-mode#4] opened 2012-10-25 14:49 UTC
Hello @ppareit,

Thanks for making this; I got envious of my boss' vim highlighting, so I had to try this out!  Thanks for helping me keep some of my dignity... ;-)

I added this mode to my init.el and on reloading got the above error.  Some further digging online suggests that this is a collision with autopair mode - have you been able to reproduce this?  

FYI: I found a workaround here:  http://www.cnblogs.com/csophys/archive/2012/03/10/2389504.html

**Comment by ppareit** [comment] 2020-01-25 10:43
I've added autopair to my configuration and was unable to reproduce. I'm closing this, but don't hesitate to reopen if the issue is still showing.

**Closed by ppareit** 2020-01-25 10:43 UTC
